version: "3.9"
services:
  backend:
    build: .
    restart: on-failure:5
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - libretranslate

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: